---

- name: "Install common {{ packages | list }} for 1c app and postgresql"
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - gnupg2
    - libicu-dev
    - icu-doc
    - libicu-dev
    - ssl-cert
    - python-psycopg2
    - python3-psycopg2

- name: "Install a .deb packages from the internet"
  apt:
    deb: "{{ item }}"
  loop:
    - "http://security.ubuntu.com/ubuntu/pool/main/o/openssl1.0/libssl1.0.0_1.0.2n-1ubuntu5.3_amd64.deb"
    - "http://security.ubuntu.com/ubuntu/pool/main/i/icu/libicu55_55.1-7ubuntu0.4_amd64.deb"
    - "http://security.ubuntu.com/ubuntu/pool/main/p/postgresql-common/postgresql-client-common_199ubuntu0.1_all.deb"
    - "http://security.ubuntu.com/ubuntu/pool/main/p/postgresql-common/postgresql-common_199ubuntu0.1_all.deb"

- name: "Install PostgreSQL for 1c from S3"
  apt:
    deb: "{{ item }}"
  loop:
    - "https://filesvy38.s3.eu-central-1.amazonaws.com/deb/postgresql11.5/libpq5_11.5-1.1C_amd64.deb"
    - "https://filesvy38.s3.eu-central-1.amazonaws.com/deb/postgresql11.5/postgresql-client-11_11.5-1.1C_amd64.deb"
    - "https://filesvy38.s3.eu-central-1.amazonaws.com/deb/postgresql11.5/postgresql-11_11.5-1.1C_amd64.deb"
    - "https://filesvy38.s3.eu-central-1.amazonaws.com/deb/postgresql11.5/postgresql-plperl-11_11.5-1.1C_amd64.deb"
    - "https://filesvy38.s3.eu-central-1.amazonaws.com/deb/postgresql11.5/postgresql-plpython3-11_11.5-1.1C_amd64.deb"
    - "https://filesvy38.s3.eu-central-1.amazonaws.com/deb/postgresql11.5/postgresql-pltcl-11_11.5-1.1C_amd64.deb"
    - "https://filesvy38.s3.eu-central-1.amazonaws.com/deb/postgresql11.5/postgresql-doc-11_11.5-1.1C_all.deb"
    - "https://filesvy38.s3.eu-central-1.amazonaws.com/deb/postgresql11.5/libecpg6_11.5-1.1C_amd64.deb"
    - "https://filesvy38.s3.eu-central-1.amazonaws.com/deb/postgresql11.5/libecpg-compat3_11.5-1.1C_amd64.deb"
    - "https://filesvy38.s3.eu-central-1.amazonaws.com/deb/postgresql11.5/libpgtypes3_11.5-1.1C_amd64.deb"
    - "https://filesvy38.s3.eu-central-1.amazonaws.com/deb/postgresql11.5/libpq-dev_11.5-1.1C_amd64.deb"
    - "https://filesvy38.s3.eu-central-1.amazonaws.com/deb/postgresql11.5/postgresql-11-dbg_11.5-1.1C_amd64.deb"
    - "https://filesvy38.s3.eu-central-1.amazonaws.com/deb/postgresql11.5/postgresql-pltcl-11_11.5-1.1C_amd64.deb"
    - "https://filesvy38.s3.eu-central-1.amazonaws.com/deb/postgresql11.5/postgresql-server-dev-11_11.5-1.1C_amd64.deb"
    - "https://filesvy38.s3.eu-central-1.amazonaws.com/deb/postgresql11.5/libecpg-dev_11.5-1.1C_amd64.deb"
  notify: "Enable service postgresql and set state started"

- name: "Set hold postgresql"
  dpkg_selections:
    name: "postgresql"
    selection: hold

- name: "Push Postgresql config"
  template:
    src: "roles/postgresql/templates/postgresql.conf.j2"
    dest: "/etc/postgresql/11/main/postgresql.conf"
    owner: postgres
    group: postgres
    mode: u=rw,g=r,o=r
  notify: "Reboot Postgresql that postgresql.conf changes to apply"

- name: "Ensure database is created"
  become_user: postgres
  become: "yes"
  postgresql_db:
    name: "{{ item.1.db_name }}"
    encoding: 'UTF-8'
    lc_collate: 'ru_RU.UTF-8'
    lc_ctype: 'ru_RU.UTF-8'
    template: 'template0'
    state: present
  loop: "{{ databases | dict2items | subelements('value.set') }}"

- name: "Ensure user has access to the database"
  become_user: postgres
  become: "yes"
  postgresql_user:
    db: "{{ item.1.db_name }}"
    name: "{{ item.1.user.name }}"
    password: "{{ item.1.user.password }}"
    priv: ALL
    state: present
  loop: "{{ databases | dict2items | subelements('value.set') }}"

- name: "Ensure user does not have unnecessary privileges"
  become_user: postgres
  become: "yes"
  postgresql_user:
    name: "{{ item.1.user.name }}"
    role_attr_flags: NOSUPERUSER,NOCREATEDB
    state: present
  loop: "{{ databases | dict2items | subelements('value.set') }}"
