---

- name: "Install common {{ packages | list }} for 1c app and postgresql"
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - gnupg2
    - libicu-dev
    - icu-doc
    - libicu-dev
    - ssl-cert
    - python-psycopg2
    - python3-psycopg2

- name: "Install a .deb packages from the internet"
  apt:
    deb: "{{ item }}"
  loop:
    - "http://security.ubuntu.com/ubuntu/pool/main/o/openssl1.0/libssl1.0.0_1.0.2n-1ubuntu5.3_amd64.deb"
    - "http://security.ubuntu.com/ubuntu/pool/main/i/icu/libicu55_55.1-7ubuntu0.5_amd64.deb"
    - "http://security.ubuntu.com/ubuntu/pool/main/p/postgresql-common/postgresql-client-common_190ubuntu0.1_all.deb"
    - "http://security.ubuntu.com/ubuntu/pool/main/p/postgresql-common/postgresql-common_190ubuntu0.1_all.deb"

- name: "Extract /root/postgresql_9.6.7_1.1C_amd64_addon_deb.tar.bz2 /tmp"
  unarchive:
    src: /root/postgresql_9.6.7_1.1C_amd64_addon_deb.tar.bz2
    dest: /tmp
    remote_src: yes

- name: "Extract /root/postgresql_9.6.7_1.1C_amd64_deb.tar.bz2 /tmp"
  unarchive:
    src: /root/postgresql_9.6.7_1.1C_amd64_deb.tar.bz2
    dest: /tmp
    remote_src: yes

- name: "Install PostgreSQL for 1c from S3"
  apt:
    deb: "{{ item }}"
  loop:
    - "/tmp/postgresql-9.6.7-1.1C_amd64_deb/libpq5_9.6.7-1.1C_amd64.deb"
    - "/tmp/postgresql-9.6.7-1.1C_amd64_addon_deb/libpq-dev_9.6.7-1.1C_amd64.deb"
    - "/tmp/postgresql-9.6.7-1.1C_amd64_addon_deb/libecpg6_9.6.7-1.1C_amd64.deb"
    - "/tmp/postgresql-9.6.7-1.1C_amd64_addon_deb/libecpg-compat3_9.6.7-1.1C_amd64.deb"
    - "/tmp/postgresql-9.6.7-1.1C_amd64_addon_deb/libpgtypes3_9.6.7-1.1C_amd64.deb"
    - "/tmp/postgresql-9.6.7-1.1C_amd64_addon_deb/libpq-dev_9.6.7-1.1C_amd64.deb"
    - "/tmp/postgresql-9.6.7-1.1C_amd64_addon_deb/postgresql-doc-9.6_9.6.7-1.1C_all.deb"
    - "/tmp/postgresql-9.6.7-1.1C_amd64_addon_deb/postgresql-server-dev-9.6_9.6.7-1.1C_amd64.deb"
    - "/tmp/postgresql-9.6.7-1.1C_amd64_deb/postgresql-client-9.6_9.6.7-1.1C_amd64.deb"
    - "/tmp/postgresql-9.6.7-1.1C_amd64_deb/postgresql-9.6_9.6.7-1.1C_amd64.deb"
    - "/tmp/postgresql-9.6.7-1.1C_amd64_deb/postgresql-contrib-9.6_9.6.7-1.1C_amd64.deb"
    - "/tmp/postgresql-9.6.7-1.1C_amd64_addon_deb/libecpg-dev_9.6.7-1.1C_amd64.deb"
    - "/tmp/postgresql-9.6.7-1.1C_amd64_addon_deb/postgresql-9.6-dbg_9.6.7-1.1C_amd64.deb"
    - "/tmp/postgresql-9.6.7-1.1C_amd64_addon_deb/postgresql-plperl-9.6_9.6.7-1.1C_amd64.deb"
    - "/tmp/postgresql-9.6.7-1.1C_amd64_addon_deb/postgresql-plpython3-9.6_9.6.7-1.1C_amd64.deb"
    - "/tmp/postgresql-9.6.7-1.1C_amd64_addon_deb/postgresql-plpython-9.6_9.6.7-1.1C_amd64.deb"
    - "/tmp/postgresql-9.6.7-1.1C_amd64_addon_deb/postgresql-pltcl-9.6_9.6.7-1.1C_amd64.deb"

  notify: "Enable service postgresql and set state started"

- name: "Set hold postgresql"
  dpkg_selections:
    name: "postgresql"
    selection: hold

- name: "Push Postgresql config"
  template:
    src: "roles/postgresql/templates/postgresql.conf.j2"
    dest: "/etc/postgresql/9.6/main/postgresql.conf"
    owner: postgres
    group: postgres
    mode: u=rw,g=r,o=r
  notify: "Reboot Postgresql that postgresql.conf changes to apply"
