---

- hosts: serv1c8
  remote_user: deploy
  become: "yes"
  become_user: "root"
  become_method: "sudo"
  gather_facts: true

  vars:
    servername: "{{ inventory_hostname }}"
    docker_users:
      - deploy
      - goto
    ufw_state: disabled

  roles:
    - { role: info, tags: ['info'] }
    - { role: common, tags: ['common'] }
    - { role: docker, tags: ['docker'] }
    - { role: docker-compose, tags: ['docker-compose'] }
    - { role: postgresql, tags: ['postgresql'] }
    - { role: srv1cv83, tags: ['srv1cv83'] }
    - { role: maintenance, tags: ['maintenance'] }
    - { role: auto1c, tags: ['auto1c'] }
    - { role: ufw, tags: ['ufw'] }
