---
- name: "Download file from s3 bucket with check (md5)"
  get_url:
    url: "https://filesvy38.s3.eu-central-1.amazonaws.com/win/auto1c.tgz"
    dest: /tmp
    checksum: md5:98771d253859ca309c353c4919ec6c4c

- name: "1c from S3 bucket"
  unarchive:
    src: "/tmp/auto1c.tgz"
    dest: "{{ path_auto1c }}"
    remote_src: yes
    group: "{{ folder_name_for_auto1c }}"
    mode: u=rw,g=rwx,o=rx

- name: "Push 1cescmn.cfg"
  template:
    src: "roles/auto1c/templates/1cescmn.cfg"
    dest: "{{ path_auto1c }}/1cescmn.cfg"
    owner: root
    group: "{{ folder_name_for_auto1c }}"
    mode: u=rw,g=rwx,o=rx

- name: "Push ibases.v8i"
  template:
    src: "roles/auto1c/templates/ibases.v8i"
    dest: "{{ path_auto1c }}/ibases.v8i"
    owner: root
    group: "{{ folder_name_for_auto1c }}"
    mode: u=rw,g=rwx,o=rx
