---

- name: "Install windows fonts"
  apt:
    name: ttf-mscorefonts-installer
  notify: "Update the font cache"


- name: "Install a .deb packages from S3"
  apt:
    deb: "{{ item }}"
  loop:
    - "https://filesvy38.s3.eu-central-1.amazonaws.com/deb/8.3.15.1565/x64/1c-enterprise83-common_8.3.15-1565_amd64.deb"
    - "https://filesvy38.s3.eu-central-1.amazonaws.com/deb/8.3.15.1565/x64/1c-enterprise83-server_8.3.15-1565_amd64.deb"
    - "https://filesvy38.s3.eu-central-1.amazonaws.com/deb/8.3.15.1565/x64/1c-enterprise83-ws_8.3.15-1565_amd64.deb"
    - "https://filesvy38.s3.eu-central-1.amazonaws.com/deb/8.3.15.1565/x64/1c-enterprise83-client_8.3.15-1565_amd64.deb"
    - "https://filesvy38.s3.eu-central-1.amazonaws.com/deb/8.3.15.1565/x64/1c-enterprise83-crs_8.3.15-1565_amd64.deb"
  notify: "Enable service srv1cv83 and set state started"
