---

- name: "Recommended packages for 1c on the Ubuntnu 16.04"
  apt:
    name: "{{ item }}"
  notify: "Update the font cache"
  loop:
    - ttf-mscorefonts-installer
    - fontconfig
    - libfreetype6
    - libgsf-1-114
    - glib-networking
    - glib-networking-common
    - glib-networking-services
    - unixodbc
    - libkrb5-26-heimdal
    - libkrb5-3
    - libkrb5support0
    - libgssapi-krb5-2

- name: "Install a .deb packages from S3"
  apt:
    deb: "{{ item }}"
  loop:
    - "https://filesvy38.s3.eu-central-1.amazonaws.com/deb/8.3.15.1565/x64/1c-enterprise83-common_8.3.15-1565_amd64.deb"
    - "https://filesvy38.s3.eu-central-1.amazonaws.com/deb/8.3.15.1565/x64/1c-enterprise83-server_8.3.15-1565_amd64.deb"
    - "https://filesvy38.s3.eu-central-1.amazonaws.com/deb/8.3.15.1565/x64/1c-enterprise83-ws_8.3.15-1565_amd64.deb"
    - "https://filesvy38.s3.eu-central-1.amazonaws.com/deb/8.3.15.1565/x64/1c-enterprise83-client_8.3.15-1565_amd64.deb"
    - "https://filesvy38.s3.eu-central-1.amazonaws.com/deb/8.3.15.1565/x64/1c-enterprise83-crs_8.3.15-1565_amd64.deb"
  notify: "Enable service srv1cv83 and set state started"
