---

- name: "Recommended packages for 1c on the Ubuntnu 16.04"
  apt:
    name: "{{ item }}"
  notify: "Update the font cache"
  loop:
    - ttf-mscorefonts-installer
    - fontconfig
    - libfreetype6
    - libgsf-1-114
    - glib-networking
    - glib-networking-common
    - glib-networking-services
    - unixodbc
    - libkrb5-26-heimdal
    - libkrb5-3
    - libkrb5support0
    - libgssapi-krb5-2

- name: "Extract /root/deb64_8_3_16_1148.tar.gz /tmp"
  unarchive:
    src: /root/deb64_8_3_16_1148.tar.gz
    dest: /tmp
    remote_src: yes

- name: "Extract /root/client_8_3_16_1148.deb64.tar.gz /tmp"
  unarchive:
    src: /root/client_8_3_16_1148.deb64.tar.gz
    dest: /tmp
    remote_src: yes

- name: "Install a .deb packages from S3"
  apt:
    deb: "{{ item }}"
  loop:
    - "/tmp/1c-enterprise83-common_8.3.16-1148_amd64.deb"
    - "/tmp/1c-enterprise83-server_8.3.16-1148_amd64.deb"
    - "/tmp/1c-enterprise83-ws_8.3.16-1148_amd64.deb"
    - "/tmp/1c-enterprise83-client_8.3.16-1148_amd64.deb"
    - "/tmp/1c-enterprise83-crs_8.3.16-1148_amd64.deb"
  notify: "Enable service srv1cv83 and set state started"
