---
- name: "Install ufw"
  apt:
    name: ufw

- name: "Allow enable UFW"
  ufw:
    state: "{{ ufw_state }}"

- name: "Openning ports for list services"
  ufw:
    rule: allow
    name: "{{ item }}"
  loop: "{{ ufw_profiles }}"

- name: "Opening ports for Postgresql"
  ufw:
    rule: allow
    port: '5432'
    proto: 'tcp'
    src: "{{ item }}"
  loop:
    - 127.0.0.1/32

- name: "Opening ports for 1c: 1540-1541"
  ufw:
    rule: allow
    port: '1540:1541'
    proto: 'tcp'
    src: "{{ item }}"
  loop:
    - "{{ ansible_default_ipv4.network }}/{{ ansible_default_ipv4.netmask }}"

- name: "Opening ports for 1c: 1560-1591"
  ufw:
    rule: allow
    port: '1560:1591'
    proto: 'tcp'
    src: "{{ item }}"
  loop:
    - "{{ ansible_default_ipv4.network }}/{{ ansible_default_ipv4.netmask }}"
