---

- name: "Update cache"
  apt:
    update_cache: "yes"

- name: "Enable service postgresql and set state started"
  systemd:
    name: postgresql.service
    enabled: "yes"
    state: started

- name: "Reboot Postgresql that smb.conf changes to apply"
  systemd:
    name: postgresql.service
    state: restarted
